
NUTANIX_USERNAME     = "admin"
NUTANIX_PASSWORD     = "nx2Tech402!"
NUTANIX_ENDPOINT     = "10.42.41.39"
NUTANIX_INSECURE     = true
NUTANIX_PORT         = 9440
NUTANIX_WAIT_TIMEOUT = 10
EXTERNAL_SUBNET = "EXTERNAL-SUBNET"

