//Provider
NUTANIX_USERNAME     = "admin"
NUTANIX_PASSWORD     = "Security/4u"
NUTANIX_ENDPOINT     = "10.54.25.40"
NUTANIX_INSECURE     = true
NUTANIX_PORT         = 9440
NUTANIX_WAIT_TIMEOUT = 10
EXTERNAL_VLAN = "vlan1060-external"

